name: "chat-app-ui-dev"
services:
  chat-app-ui:
    container_name: 'chat-app-ui'
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        VITE_REST_API_BASE_URL: ${VITE_REST_API_BASE_URL}
        VITE_REST_API_ROOT_PATH: ${VITE_REST_API_ROOT_PATH}
        VITE_REST_API_VERSION: ${VITE_REST_API_VERSION}
        SERVE_PORT: ${SERVE_PORT}
    ports:
      - ${SERVE_PORT}:${SERVE_PORT}
