name: "chat-app-ui-dev"
services:
  chat-app-ui:
    container_name: 'chat-app-ui'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${VITE_SERVE_PORT}:${VITE_SERVE_PORT}
    environment:
      VITE_REST_API_BASE_URL: ${VITE_REST_API_BASE_URL}
      VITE_REST_API_ROOT_PATH: ${VITE_REST_API_ROOT_PATH}
      VITE_REST_API_VERSION: ${VITE_REST_API_VERSION}
      VITE_SERVE_PORT: ${VITE_SERVE_PORT}
