name: "chat-app-ui-dev"
services:
  chat-app-ui:
    container_name: 'chat-app-ui'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    environment:
      VITE_SERVE_PORT: 8080
