name: "chat-app-dev"
services:
  chat-app-mongo:
    container_name: 'chat-app-mongo'
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./.data/db:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DB: ${DB_NAME}

  chat-app-rabbitmq:
    container_name: 'chat-app-rabbitmq'
    image: rabbitmq:3-management-alpine
    ports:
        - ${AMQP_PORT}:${AMQP_PORT}
        - ${AMQP_UI_PORT}:${AMQP_UI_PORT}
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  api:
    container_name: 'chat-app-api'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
